# Generated by Django 5.2.12 on 2026-05-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип активности',
                'verbose_name_plural': 'Типы активности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Звездная система',
                'verbose_name_plural': 'Звездные системы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='Фото')),
                ('object_type', models.CharField(choices=[('planet', 'Планета'), ('satellite', 'Спутник'), ('orbital_station', 'Орбитальная станция'), ('asteroid', 'Астероид')], max_length=32, verbose_name='Тип объекта')),
                ('tags', models.ManyToManyField(blank=True, related_name='destinations', to='accounts.activitytag', verbose_name='Типы активности')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='accounts.starsystem', verbose_name='Звездная система')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('economy', 'Economy'), ('explorer', 'Explorer'), ('first_class', 'First Class')], max_length=24, verbose_name='Класс обслуживания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('features', models.TextField(verbose_name='Преимущества тарифа')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.destination', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Пакет обслуживания',
                'verbose_name_plural': 'Пакеты обслуживания',
                'ordering': ('price',),
            },
        ),
    ]
