# Generated by Django 5.2.12 on 2026-05-04 16:26

from django.db import migrations


def create_initial_tour_catalog(apps, schema_editor):
    """Заполняет каталог стартовыми системами, тегами, направлениями и тарифами."""

    StarSystem = apps.get_model("accounts", "StarSystem")
    ActivityTag = apps.get_model("accounts", "ActivityTag")
    Destination = apps.get_model("accounts", "Destination")
    TourPackage = apps.get_model("accounts", "TourPackage")

    systems = {}
    for name in ("Внутренние планеты", "Дальний космос"):
        systems[name], _ = StarSystem.objects.get_or_create(name=name)

    tags = {}
    for name in ("Экстрим", "Исследования", "Релакс"):
        tags[name], _ = ActivityTag.objects.get_or_create(name=name)

    destinations = [
        {
            "title": "Лунная база Альфа",
            "description": "Мягкий старт для первого космического путешествия: обзор Земли, прогулка по куполу базы и короткая исследовательская программа.",
            "image": "destinations/moon-alpha.jpg",
            "object_type": "satellite",
            "system": systems["Внутренние планеты"],
            "tags": [tags["Релакс"], tags["Исследования"]],
            "packages": [
                {
                    "class_type": "economy",
                    "price": "50000.00",
                    "features": "Облет без высадки, базовое питание, групповая каюта.",
                },
                {
                    "class_type": "explorer",
                    "price": "85000.00",
                    "features": "Высадка на базу, экскурсия по куполу, персональный инструктор.",
                },
            ],
        },
        {
            "title": "Долина Маринер на Марсе",
            "description": "Экспедиционный маршрут по марсианским каньонам с ровером, геологическим модулем и видом на красные равнины.",
            "image": "destinations/mars-valles-marineris.jpg",
            "object_type": "planet",
            "system": systems["Внутренние планеты"],
            "tags": [tags["Экстрим"], tags["Исследования"]],
            "packages": [
                {
                    "class_type": "explorer",
                    "price": "120000.00",
                    "features": "Марсианский ровер, научный гид, проживание в экспедиционном модуле.",
                },
                {
                    "class_type": "first_class",
                    "price": "240000.00",
                    "features": "Панорамный модуль, расширенный маршрут, приватный экипаж сопровождения.",
                },
            ],
        },
        {
            "title": "Орбитальная станция Альфа Центавра",
            "description": "Дальний межзвездный тур для опытных путешественников с наблюдением двойной звездной системы и длительным пребыванием на станции.",
            "image": "destinations/alpha-centauri-station.jpg",
            "object_type": "orbital_station",
            "system": systems["Дальний космос"],
            "tags": [tags["Релакс"], tags["Исследования"]],
            "packages": [
                {
                    "class_type": "first_class",
                    "price": "1500000.00",
                    "features": "Криосон, индивидуальная каюта, научная программа и консьерж станции.",
                },
            ],
        },
    ]

    for destination_data in destinations:
        package_data = destination_data.pop("packages")
        tag_data = destination_data.pop("tags")
        destination, _ = Destination.objects.update_or_create(
            title=destination_data["title"],
            defaults=destination_data,
        )
        destination.tags.set(tag_data)

        for package in package_data:
            TourPackage.objects.update_or_create(
                destination=destination,
                class_type=package["class_type"],
                defaults={
                    "price": package["price"],
                    "features": package["features"],
                },
            )


def remove_initial_tour_catalog(apps, schema_editor):
    """Откат удаляет только записи, созданные этой data migration."""

    StarSystem = apps.get_model("accounts", "StarSystem")
    ActivityTag = apps.get_model("accounts", "ActivityTag")
    Destination = apps.get_model("accounts", "Destination")

    Destination.objects.filter(
        title__in=[
            "Лунная база Альфа",
            "Долина Маринер на Марсе",
            "Орбитальная станция Альфа Центавра",
        ]
    ).delete()
    ActivityTag.objects.filter(name__in=["Экстрим", "Исследования", "Релакс"]).delete()
    StarSystem.objects.filter(name__in=["Внутренние планеты", "Дальний космос"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitytag_starsystem_destination_tourpackage'),
    ]

    operations = [
        migrations.RunPython(create_initial_tour_catalog, remove_initial_tour_catalog),
    ]
