# Generated by Django 5.2.12 on 2026-05-04 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_spacetour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Заполняется, если билет был отменен.', verbose_name='Причина отмены'),
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='payment_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='pending', max_length=16, verbose_name='Статус билета'),
        ),
        migrations.CreateModel(
            name='MedicalQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Рост, см')),
                ('weight_kg', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Вес, кг')),
                ('has_chronic_diseases', models.BooleanField(default=False, verbose_name='Есть хронические заболевания')),
                ('clearance_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Допущен'), ('rejected', 'Отклонен')], default='pending', max_length=16, verbose_name='Статус допуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_questionnaire', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Медицинская анкета',
                'verbose_name_plural': 'Медицинские анкеты',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PassengerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=32, verbose_name='Номер паспорта')),
                ('citizenship', models.CharField(max_length=120, verbose_name='Гражданство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_document', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Паспортные данные пассажира',
                'verbose_name_plural': 'Паспортные данные пассажиров',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='PreparationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название задачи')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_tasks', to='accounts.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Задача подготовки',
                'verbose_name_plural': 'Задачи подготовки',
                'ordering': ('ticket', 'title'),
            },
        ),
    ]
