# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_ticket_cancellation_reason_ticket_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="psych_quiz_passed",
            field=models.BooleanField(default=False, verbose_name="Психологический тест пройден"),
        ),
    ]
