# Generated by Codex on 2026-05-05

from datetime import datetime, timedelta
from decimal import Decimal
from uuid import uuid4

from django.conf import settings
from django.db import migrations
from django.utils import timezone


SEED_DESTINATION_TITLES = [
    "Европа: подледный океан",
    "Ганимед: skyhook-док Юпитера",
    "Ио: вулканическая обсерватория",
    "Титан: метановое побережье",
    "Орбитальный отель Aurora LEO",
    "Proxima b: линия терминатора",
    "TRAPPIST-1e: сумеречные сады",
    "Kepler-186f: купол Terra",
    "Tau Ceti e: облачный порт",
    "Церера: шахтерский хаб",
]


def aware_datetime(year, month, day, hour):
    return timezone.make_aware(datetime(year, month, day, hour, 0, 0))


def seed_expanded_catalog_and_admin_demo(apps, schema_editor):
    """Создает расширенный каталог и наполняет кабинет администратора демо-данными."""

    User = apps.get_model("auth", "User")
    StarSystem = apps.get_model("accounts", "StarSystem")
    ActivityTag = apps.get_model("accounts", "ActivityTag")
    Destination = apps.get_model("accounts", "Destination")
    TourPackage = apps.get_model("accounts", "TourPackage")
    FlightSchedule = apps.get_model("accounts", "FlightSchedule")
    Ticket = apps.get_model("accounts", "Ticket")
    Achievement = apps.get_model("accounts", "Achievement")
    UserProfile = apps.get_model("accounts", "UserProfile")
    Notification = apps.get_model("accounts", "Notification")

    systems = {
        name: StarSystem.objects.get_or_create(name=name)[0]
        for name in (
            "Система Юпитера",
            "Система Сатурна",
            "Околоземная орбита",
            "Пояс астероидов",
            "Proxima Centauri",
            "TRAPPIST-1",
            "Kepler-186",
            "Tau Ceti",
        )
    }
    tags = {
        name: ActivityTag.objects.get_or_create(name=name)[0]
        for name in ("Экстрим", "Исследования", "Релакс", "Люкс", "Фототур", "Гастрономия")
    }

    catalog = [
        {
            "title": "Европа: подледный океан",
            "description": "Экспедиция к ледяной коре Европы с обзором трещин, посадкой у научного купола и симуляцией спуска к океану.",
            "image": "destinations/europa-ocean.jpg",
            "object_type": "satellite",
            "system": systems["Система Юпитера"],
            "tags": [tags["Исследования"], tags["Фототур"]],
            "seats": 18,
            "packages": [
                ("explorer", Decimal("180000.00"), "Ледовая экспедиция, научный инструктор, панорамная капсула."),
                ("first_class", Decimal("320000.00"), "Приватный модуль, личный астрофотограф, расширенный маршрут."),
            ],
        },
        {
            "title": "Ганимед: skyhook-док Юпитера",
            "description": "Переход через орбитальный skyhook с видом на Юпитер и тренировкой стыковки в низкой гравитации.",
            "image": "destinations/ganymede-skyhook.jpg",
            "object_type": "satellite",
            "system": systems["Система Юпитера"],
            "tags": [tags["Экстрим"], tags["Исследования"]],
            "seats": 12,
            "packages": [
                ("economy", Decimal("125000.00"), "Групповая капсула, обзорная палуба, базовый инструктаж."),
                ("explorer", Decimal("210000.00"), "Тренировка стыковки, доступ к док-симулятору, расширенный рацион."),
            ],
        },
        {
            "title": "Ио: вулканическая обсерватория",
            "description": "Короткая экстремальная миссия к безопасной орбитальной точке наблюдения за вулканическими выбросами Ио.",
            "image": "destinations/io-volcano.jpg",
            "object_type": "satellite",
            "system": systems["Система Юпитера"],
            "tags": [tags["Экстрим"], tags["Фототур"]],
            "seats": 8,
            "packages": [
                ("explorer", Decimal("260000.00"), "Защитный модуль, орбитальная съемка, гид-планетолог."),
                ("first_class", Decimal("430000.00"), "Лучшие окна обсерватории, приватный экипаж, премиальная страховка."),
            ],
        },
        {
            "title": "Титан: метановое побережье",
            "description": "Путешествие к атмосферным куполам Титана с прогулкой по смотровым галереям над метановыми озерами.",
            "image": "destinations/titan-coast.jpg",
            "object_type": "satellite",
            "system": systems["Система Сатурна"],
            "tags": [tags["Релакс"], tags["Исследования"], tags["Гастрономия"]],
            "seats": 20,
            "packages": [
                ("economy", Decimal("170000.00"), "Обзорная станция, групповая каюта, базовая экскурсия."),
                ("first_class", Decimal("390000.00"), "Купольный люкс, шеф-меню станции, закрытый маршрут у озер."),
            ],
        },
        {
            "title": "Орбитальный отель Aurora LEO",
            "description": "Премиальный уикенд на низкой орбите Земли: рассветы каждые 90 минут, zero-g spa и купольный ресторан.",
            "image": "destinations/aurora-leo-hotel.jpg",
            "object_type": "orbital_station",
            "system": systems["Околоземная орбита"],
            "tags": [tags["Люкс"], tags["Релакс"], tags["Гастрономия"]],
            "seats": 32,
            "packages": [
                ("economy", Decimal("65000.00"), "Двухместная каюта, обзорная палуба, завтрак на орбите."),
                ("first_class", Decimal("185000.00"), "Личный модуль, zero-g spa, дегустационный сет."),
            ],
        },
        {
            "title": "Proxima b: линия терминатора",
            "description": "Дальний тур к зоне вечных сумерек экзопланеты Proxima b с наблюдением красного карлика.",
            "image": "destinations/proxima-b-terminator.jpg",
            "object_type": "planet",
            "system": systems["Proxima Centauri"],
            "tags": [tags["Исследования"], tags["Фототур"]],
            "seats": 6,
            "packages": [
                ("explorer", Decimal("2400000.00"), "Криосон, научный блок, длительное пребывание на станции."),
                ("first_class", Decimal("4200000.00"), "Индивидуальная капсула сна, приватная лаборатория, консьерж миссии."),
            ],
        },
        {
            "title": "TRAPPIST-1e: сумеречные сады",
            "description": "Маршрут к терраформируемому биокуполу на TRAPPIST-1e с прогулкой по закрытым ботаническим секторам.",
            "image": "destinations/trappist-1e-gardens.jpg",
            "object_type": "planet",
            "system": systems["TRAPPIST-1"],
            "tags": [tags["Релакс"], tags["Исследования"]],
            "seats": 10,
            "packages": [
                ("explorer", Decimal("1900000.00"), "Биокупол, научный гид, экспедиционная каюта."),
                ("first_class", Decimal("3500000.00"), "Люкс в куполе, персональная экскурсия, расширенный фотоархив."),
            ],
        },
        {
            "title": "Kepler-186f: купол Terra",
            "description": "Экзопланетная база с симуляцией земной гравитации и обзором красноватого неба Kepler-186f.",
            "image": "destinations/kepler-186f-terra.jpg",
            "object_type": "planet",
            "system": systems["Kepler-186"],
            "tags": [tags["Люкс"], tags["Исследования"]],
            "seats": 9,
            "packages": [
                ("explorer", Decimal("2100000.00"), "Купол Terra, гравитационная адаптация, экспедиционный рацион."),
                ("first_class", Decimal("3800000.00"), "Персональный habitat, приватный гид, расширенный медсопровождающий пакет."),
            ],
        },
        {
            "title": "Tau Ceti e: облачный порт",
            "description": "Орбитальный порт над плотными облачными слоями Tau Ceti e с курсом навигации в дальнем космосе.",
            "image": "destinations/tau-ceti-e-cloudport.jpg",
            "object_type": "planet",
            "system": systems["Tau Ceti"],
            "tags": [tags["Исследования"], tags["Люкс"]],
            "seats": 7,
            "packages": [
                ("explorer", Decimal("1750000.00"), "Курс навигации, обзорный модуль, научные брифинги."),
                ("first_class", Decimal("3100000.00"), "Панорамный suite, приватная палуба, персональный офицер связи."),
            ],
        },
        {
            "title": "Церера: шахтерский хаб",
            "description": "Промышленный тур в пояс астероидов: подземные тоннели, добывающие модули и учебный EVA-выход.",
            "image": "destinations/ceres-mining-hub.jpg",
            "object_type": "asteroid",
            "system": systems["Пояс астероидов"],
            "tags": [tags["Экстрим"], tags["Исследования"]],
            "seats": 14,
            "packages": [
                ("economy", Decimal("95000.00"), "Групповая каюта, тоннельный маршрут, промышленный инструктаж."),
                ("explorer", Decimal("155000.00"), "Учебный EVA-выход, доступ к командному мосту, расширенный маршрут."),
            ],
        },
    ]

    base_departure = aware_datetime(2026, 7, 3, 11)
    seeded_destinations = []
    for index, destination_data in enumerate(catalog):
        package_data = destination_data.pop("packages")
        tag_data = destination_data.pop("tags")
        seats = destination_data.pop("seats")
        destination, _ = Destination.objects.update_or_create(
            title=destination_data["title"],
            defaults=destination_data,
        )
        destination.tags.set(tag_data)
        seeded_destinations.append(destination)

        for class_type, price, features in package_data:
            TourPackage.objects.update_or_create(
                destination=destination,
                class_type=class_type,
                defaults={"price": price, "features": features},
            )

        for offset in (0, 21):
            FlightSchedule.objects.update_or_create(
                destination=destination,
                departure_at=base_departure + timedelta(days=index * 8 + offset),
                defaults={"available_seats": seats if offset == 0 else max(seats - 3, 1)},
            )

    admin = User.objects.filter(is_superuser=True).order_by("id").first()
    if not admin:
        return

    profile, _ = UserProfile.objects.get_or_create(user=admin, defaults={"age": 30})
    profile.psych_quiz_passed = True
    profile.save(update_fields=["psych_quiz_passed", "updated_at"])

    achievement_data = [
        ("Первый старт", "Первый оформленный билет Travel X.", "achievements/first-start.png"),
        ("Покоритель Юпитера", "Забронирован маршрут в системе Юпитера.", "achievements/jupiter.png"),
        ("Орбитальный гурман", "Выбран тур с гастрономической программой.", "achievements/orbital-gourmet.png"),
    ]
    for title, description, icon in achievement_data:
        achievement, _ = Achievement.objects.get_or_create(
            title=title,
            defaults={"description": description, "icon": icon},
        )
        profile.achievements.add(achievement)

    for destination in seeded_destinations[:2]:
        package = TourPackage.objects.filter(destination=destination).order_by("price").first()
        schedule = FlightSchedule.objects.filter(destination=destination, available_seats__gt=0).order_by("departure_at").first()
        if not package or not schedule:
            continue

        if not Ticket.objects.filter(user=admin, package=package, flight_schedule=schedule).exists():
            Ticket.objects.create(
                user=admin,
                package=package,
                flight_schedule=schedule,
                ticket_number=uuid4(),
                status="paid",
            )
            schedule.available_seats = max(schedule.available_seats - 1, 0)
            schedule.save(update_fields=["available_seats", "updated_at"])

    for text in (
        "Подготовка к рейсу Travel X активирована: проверьте документы и медицинский допуск.",
        "Для вашего маршрута доступен новый брифинг по безопасности в личном кабинете.",
        "До ближайшего старта осталось меньше месяца: экипаж подтвердит детали за 72 часа.",
    ):
        Notification.objects.get_or_create(user=admin, text=text, defaults={"is_read": False})


def remove_expanded_catalog_and_admin_demo(apps, schema_editor):
    """Откат удаляет только каталог и демо-записи, созданные этой миграцией."""

    User = apps.get_model("auth", "User")
    Destination = apps.get_model("accounts", "Destination")
    Ticket = apps.get_model("accounts", "Ticket")
    Notification = apps.get_model("accounts", "Notification")

    admin = User.objects.filter(is_superuser=True).order_by("id").first()
    if admin:
        Ticket.objects.filter(user=admin, package__destination__title__in=SEED_DESTINATION_TITLES).delete()
        Notification.objects.filter(
            user=admin,
            text__in=[
                "Подготовка к рейсу Travel X активирована: проверьте документы и медицинский допуск.",
                "Для вашего маршрута доступен новый брифинг по безопасности в личном кабинете.",
                "До ближайшего старта осталось меньше месяца: экипаж подтвердит детали за 72 часа.",
            ],
        ).delete()

    Destination.objects.filter(title__in=SEED_DESTINATION_TITLES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_userprofile_psych_quiz_passed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_expanded_catalog_and_admin_demo, remove_expanded_catalog_and_admin_demo),
    ]
